// My custom header
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Member = { name: string; user_id: string; avatar: string | null; color: string | null }

export type MemberList = { name: string; members: Member[] }

export type PresenceMember = { user_id: string; last_seen: number }

export type ProceduresLegacy = { queries: { key: "auth_refresh_token"; input: string; result: { access_token: string; refresh_token: string } }; mutations: { key: "auth_login"; input: { username: string; password: string }; result: { access_token: string; refresh_token: string } } | { key: "lobby_create"; input: null; result: { join_code: string; member_list: MemberList[] } } | { key: "lobby_join"; input: string; result: { join_code: string; member_list: MemberList[] } }; subscriptions: { key: "lobby_subscribe"; input: { join_code: string; access_token: string }; result: { presence: Partial<{ [key in string]: PresenceMember }> } } }

export type Procedures = {
	auth_login: { kind: "mutation", input: { username: string; password: string }, output: { access_token: string; refresh_token: string }, error: unknown },
	auth_refresh_token: { kind: "query", input: string, output: { access_token: string; refresh_token: string }, error: unknown },
	lobby_create: { kind: "mutation", input: null, output: { join_code: string; member_list: MemberList[] }, error: unknown },
	lobby_join: { kind: "mutation", input: string, output: { join_code: string; member_list: MemberList[] }, error: unknown },
	lobby_subscribe: { kind: "subscription", input: { join_code: string; access_token: string }, output: { presence: Partial<{ [key in string]: PresenceMember }> }, error: unknown },
}