// My custom header
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Edge<T> = { cursor: string; node: T }

export type PageInfo = { has_next_page: boolean; has_prev_page: boolean; start_cursor: string | null; end_cursor: string | null; total_count: number }

export type ProceduresLegacy = { queries: { key: "auth_refresh_token"; input: string; result: { access_token: string; refresh_token: string } } | { key: "channel_list_in"; input: string; result: { page_info: PageInfo; edges: Edge<T>[]; meta: M } }; mutations: { key: "auth_login"; input: { username: string; password: string }; result: { access_token: string; refresh_token: string } }; subscriptions: never }

export type Procedures = {
	auth_login: { kind: "mutation", input: { username: string; password: string }, output: { access_token: string; refresh_token: string }, error: unknown },
	auth_refresh_token: { kind: "query", input: string, output: { access_token: string; refresh_token: string }, error: unknown },
	channel_list_in: { kind: "query", input: string, output: { page_info: PageInfo; edges: Edge<T>[]; meta: M }, error: unknown },
}